config/routes.rb
Dibbs::Application.routes.draw do

  devise_for :users

  resources :users, except: [:show]

  resources :users, only: [:show] do
    resources :items, only: [:index]
    resources :friendships, only: [:index, :create, :update, :destroy], controller: "friends"
  end

  resources :items, except: [:index] do
    resources :loans, only: [:create, :edit, :update]
  end

  resource :search, only: [:show]
  resource :invitations, only: [:new, :create]

  root :to => "users#edit"

end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController

  def index
    @user = User.find(current_user)
  end

  def new
    @friendship1 = Friendship.new
    @friendship2 = Friendship.new
  end

  def create
    @user = User.find(current_user)
    @friend = User.find(params[:friend_id])
    params[:friendship1] = {:user_id => @user.id, :friend_id => @friend.id, :status => 'requested'}
    params[:friendship2] = {:user_id => @friend.id, :friend_id => @user.id, :status => 'pending'}
    @friendship1 = Friendship.create(params[:friendship1])
    @friendship2 = Friendship.create(params[:friendship2])

    if @friendship1.save && @friendship2.save
      redirect_to user_friendships_path(current_user)
      flash[:notice] = "Friendship Pending."
    else
      redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(current_user)
    @friend = User.find(params[:id])
    params[:friendship1] = {:user_id => @user.id, :friend_id => @friend.id, :status => 'accepted'}
    params[:friendship2] = {:user_id => @friend.id, :friend_id => @user.id, :status => 'accepted'}
    @friendship1 = Friendship.find_by_user_id_and_friend_id(@user.id, @friend.id)
    @friendship2 = Friendship.find_by_user_id_and_friend_id(@friend.id, @user.id)

    if @friendship1.update_attributes(params[:friendship1]) && @friendship2.update_attributes(params[:friendship2])
      flash[:notice] = "Friend request accepted"
      redirect_to user_friendships_path(current_user)
    else
      redirect_to users_path(current_user)
    end
  end

  def destroy
    @user = User.find(current_user)
    @friend = User.find(params[:id])

    @friendship1 = @user.friendships.find_by_friend_id(params[:id]).destroy
    @friendship2 = @friend.friendships.find_by_user_id(params[:id]).destroy
    flash[:notice] = "Friend request removed"
    redirect_to user_friendships_path(current_user)
  end

end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/views/friends/_friends.html.erb
<div class="friends-list">
  <% unless @user.friends.empty? %>
  <table class="table">
    <tr>
      <th>Friend</th>
      <th>Status</th>
    </tr>
    <% @user.friends.each do |friend| %>
    <tr>
      <td><%= link_to friend.name, user_items_path(friend) %></td>

      <td><% if @user = current_user || current_user.pending_friends.include?(@user) || current_user.friends.include?(@user) %>
        <%= link_to ' [Unfriend] ', user_friendship_path(:user_id => current_user, :id => friend.id), :method => :delete, :confirm => 'Are you sure?' %>
      </td>
    </tr>
      <% end %>
    <% end %>
    <% else %>

     <p>None<p>

    <% end %>
  </table>
</div>

app/views/friends/_pending_friends.html.erb
<div class="view-pending">
  <% unless @user.pending_friends.empty? %>
    <% @user.pending_friends.each do |friend| %>
      <ul>
        <li><%= friend.name %>

        <% if @user == current_user %>

          <%= link_to '[Accept]', user_friendship_path(:user_id => current_user, :id => friend.id), :method => :put, :confirm => 'Accept friend request! Are you sure?' %> |
          <%= link_to '[Reject]', user_friendship_path(:user_id => current_user, :id => friend.id), :method => :delete, :confirm => 'Reject friend request! Are you sure?' %>
          <% end %>

        </li>


    <% end %>
    <% else %>

    <% end %>
     </ul>
</div>

app/views/friends/_requested_friends.html.erb
<div class="view-friendrequests">
  <% unless @user.requested_friends.empty? %>
    <% @user.requested_friends.each do |request| %>
    <ul>
      <li><%= request.name %>
        <% if @user == current_user %>
          <%= link_to '[Cancel]', user_friendship_path(:user_id => current_user, :id => request.id), :method => :delete, :confirm => 'Are you sure?' %>
          <% end %>
        <% end %>
      </li>
    </ul>
    <% else %>

  <% end %>
</div>

app/views/friends/index.html.erb
<%= render 'nav' %>

<% unless @user == current_user || current_user.requested_friends.include?(@user) || current_user.friends.include?(@user) || current_user.pending_friends.include?(@user) %>
  You do not have permission to access this page!
<% else %>

<div class="friend-container container">
  <div class="main">
    <div class="view-friends">
      <h2>My Friends</h2>
      <%= render 'friends' %>
    </div>
    <div class="aside">
      <h3>Friendship Requests</h3>
        <%= render 'requested_friends' %>
      <div class="bside">
      <h3>Pending Friendships</h3>
        <%= render 'pending_friends'  %>
      </div>
     </div>
   </div>
  <% end %>
</div>