config/routes.rb
Dibbs::Application.routes.draw do

  devise_for :users

  resources :users, except: [:show]

  resources :users, only: [:show] do
    resources :items, only: [:index]
    resources :friendships, only: [:index, :create, :update, :destroy], controller: "friends"
  end

  resources :items, except: [:index] do
    resources :loans, only: [:create, :edit, :update]
  end

  resource :search, only: [:show]
  resource :invitations, only: [:new, :create]

  root :to => "users#edit"

end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :sent_invitations,
    :class_name => 'Invitation',
    :foreign_key => "sender_id"

  belongs_to :invitation

  before_create :set_invitation_limit

  has_many :friendships,
    :dependent => :destroy

  has_many :requested_friends,
    :through => :friendships,
    :source => :friend,
    :conditions => "status = 'requested'",
    :order => :created_at

  has_many :friends,
    :through => :friendships,
    :conditions => "status = 'accepted'"

  has_many :pending_friends,
    :through => :friendships,
    :source => :friend,
    :conditions => "status = 'pending'",
    :order => :created_at

  phony_normalize :phone_number, :default_country_code => 'US'
  validates_presence_of :name
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :phone_number, :receives_notifications, :name, :email, :password, :password_confirmation, :remember_me, :friends, :friendships, :pending_friends
  # attr_accessible :title, :body

  has_many :items,
    :dependent => :destroy

  has_many :borrowers,
    :dependent => :destroy

  has_many :owners,
    :dependent => :destroy

  private

  def set_invitation_limit
    self.invitation_limit = 3
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
    @q = User.search(params[:q])
    @users = @q.result(:distinct => true)
  end

  def show
    @users = User.find(params[:id])
  end

  def edit
    @items = current_user.items
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_loaned_items.html.erb
<div class="profile">
  <table class= "table">
    <tr>
      <th>Avatar</th>
      <th>Item</th>
      <th>Status</th>
    </tr>
      <% @items.each do |item| %>
       <% unless item.currently_loaned.empty? %>
        <tr>
          <td><%= image_tag item.avatar_url(:mobile) if item.avatar? %></td>
          <td><%= link_to item.name, item_path(item), method: :get  %></td>
          <td><%= simple_form_for [item, item.loans.last] do |f| %>
             <% if item.loaned? %>
                <%= f.hidden_field :state_event, value: "return" %>
                <%= f.button :submit, "Return it!" %>
             <%- end %>
            <%- end %>
          </td>
        </tr>
      <% end %>
    <% end %>
  </table>
</div>

app/views/users/_my_items.html.erb
<div class="profile">
  <table class= "table">
    <tr>
      <th>Avatar</th>
      <th>Item</th>
      <th>Activity</th>
      <th>Category</th>
      <th>Comments</th>
      <th>Value</th>
      <th></th>
    </tr>
  <% @items.each do |item| %>
  <% unless item.loaned? || item.dibbs? %>
    <tr>
      <td><%= image_tag item.avatar_url(:mobile) if item.avatar? %></td>
      <td><%= link_to item.name, edit_item_path(item), method: :get  %></td>
      <td><%= item.activity %></td>
      <td><%= item.category %></td>
      <td><%= item.description %></td>
      <td><%= "$#{item.value}" %></td>
      <td><%= link_to 'Destroy', item_path(item), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </table>
</div>

app/views/users/_nav.html.erb
<% if user_signed_in? %>
  <div id = "nav-container">
    <div id = "nav">
      <ul>
        <li><%= link_to "My Items", edit_user_path(current_user) %></li>
        <li><%= link_to "Find Friends", users_path %></li>
        <li><%= link_to "Find Items", search_path %></li>
        <li><%= link_to "My Friendships", user_friendships_path(current_user) %></li>
        <li><%= link_to "Sign out", destroy_user_session_path, :method => "delete" %></li>
      </ul>
    </div>
  <% else %>
  <% end %>
  </div>

app/views/users/_pending_items.html.erb
<div class="profile">
  <table class= "table">
    <tr>
      <th>Avatar</th>
      <th>Item</th>
      <th>Status</th>
    </tr>
      <% @items.each do |item| %>
       <% unless item.dibbs_it.empty? %>
        <tr>
          <td><%= image_tag item.avatar_url(:mobile) if item.avatar? %></td>
          <td><%= link_to item.name, item_path(item), method: :get  %></td>
          <td><%= simple_form_for [item, item.loans.last] do |f| %>
             <% if item.dibbs? %>
                <%= f.hidden_field :state_event, value: "loan" %>
                <%= f.button :submit, "Lend it!" %>
             <%- end %>
            <%- end %>
          </td>
        </tr>
      <% end %>
    <% end %>
  </table>
</div>

app/views/users/edit.html.erb
<% unless user_signed_in? %>
  <%= form_for("user", :url => user_session_path) do |f| %>
    <%= f.label :email %> <br/>
    <%= f.text_field :email , :size=>'15',:maxlength=>'32' %> <br/>
    <%= f.label :password %> <br/>
    <%= f.password_field :password , :size=>'15', :maxlength=>'32' %>
<br/>
    <%= f.submit "Sign in" %> <br />
    <%= link_to "Forgot your password?", new_password_path('user')  %> <br/>
    <%= link_to "Sign up", new_user_registration_path %>
  <% end %>
  <% else %>
  <% end %>

  <%= render 'nav' %>

<div class="edit container">
  <div class="add"><li><%= link_to "Add Item", new_item_path %></li></div>
  <h1> My Items </h1>
    <%= render 'my_items' %>
  <h2>Pending Items</h2>
    <%= render 'pending_items' %>
  <h2>Loaned Items</h2>
    <%= render 'loaned_items'  %>


</div>

app/views/users/index.html.erb
<div class="container">
  <%= render 'nav' %>
  <div class="search-wrapper">
    <div id="search">
      <%= search_form_for @q do |f| %>
          <div class ="field">
            <%= f.text_field :name_or_email_cont, placeholder: " Enter user name or email..." %>

            <div class="actions"><%= f.submit "Search" %></div>
            <% end %>
          </div>
      </div>


      <div id="search-container">
        <div class="send-invitation">
          <% if current_user.invitation_limit > 0 %>
            <li>
              <%= link_to "Invite a friend", new_invitations_path %>
              (<%= current_user.invitation_limit %>) left
            </li>
          <% end %>
        </div>

        <table class= "table">
          <tr>
            <td><%= sort_link @q, :name, "Name" %></td>
            <td><%= sort_link @q, :email,
            "Email" %></td>
            <td></td>
          </tr>

            <% @users.each do |user| %>
              <tr>
                <% unless current_user == user || current_user.pending_friends.include?(user) || current_user.friends.include?(user) || current_user.requested_friends.include?(user) || current_user.friendships.include?(user) %>
                  <td><%= user.name %></td>
                  <td><%= user.email %></td>
                  <td>
                   <%= form_for(:friendship, :url => user_friendships_path(:user_id => current_user.id, :friend_id => user.id)) do |f| %>
                   <%= f.submit "Friend Request", :method => "post" %>
                   <% end %>
                 </td>
                <% end %>
              </tr>
            <% end %>
          </table>

        </div>
      </div>
    </div>
  </div>
</div>